/* Test program generated by configurator. */
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
int main(void) {
	int fd = open("..", O_RDONLY);
	return fchdir(fd) == 0 ? 0 : 1;
}
